name: Lint

on: [push, pull_request]

jobs:
 lint:
  name: Eslint Linter
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    node: ['lts/*']
  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup PNPM
     uses: pnpm/action-setup@v4
     with:
      standalone: true

   - name: Setup Node.js ${{ matrix.node }}
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node }}
      cache: 'pnpm'

   - name: Install dependencies
     run: pnpm install

   - name: Run ESLint
<<<<<<< HEAD
     run: pnpm lint:fix
=======
     run: pnpm lint
>>>>>>> d536d389dafe983a3846684eb7efb772c7e0bcbf
